import { lines } from '../constants';

// prettier-ignore
export const t1stations = [
    { id: 't1:RCD', x: 120, y: 190, line: lines.T1, name: 'Richmond' },
    { id: 't1:ERD', x: 120, y: 205, line: lines.T1, name: 'East Richmond' },    
    { id: 't1:CRD', x: 120, y: 220, line: lines.T1, name: 'Clarendon' },
    { id: 't1:WSR', x: 120, y: 235, line: lines.T1, name: 'Windsor' },
    { id: 't1:MUV', x: 120, y: 250, line: lines.T1, name: 'Mulgrave' },
    { id: 't1:VYR', x: 120, y: 265, line: lines.T1, name: 'Vineyard' },
    { id: 't1:RVS', x: 120, y: 280, line: lines.T1, name: 'Riverstone' },
    { id: 't1:SFS', x: 120, y: 295, line: lines.T1, name: 'Schofields' },
    { id: 't1:QKH', x: 120, y: 310, line: lines.T1, name: 'Quakers Hill' },
    { id: 't1:MYG', x: 120, y: 325, line: lines.T1, name: 'Marayong' },
    // ...
    { id: 't1:EPS', x: 35, y: 390, line: lines.T1, name: 'Emu Plains' },
    { id: 't1:PNR', x: 50, y: 390, line: lines.T1, name: 'Penrith' },
    { id: 't1:KWD', x: 65, y: 390, line: lines.T1, name: 'Kingswood' },
    { id: 't1:WRT', x: 80, y: 390, line: lines.T1, name: 'Werrington' },
    { id: 't1:STM', x: 95, y: 390, line: lines.T1, name: 'St Marys' },
    { id: 't1:MTT', x: 110, y: 390, line: lines.T1, name: 'Mount Druitt' },
    { id: 't1:RYH', x: 125, y: 390, line: lines.T1, name: 'Rooty Hill' },
    { id: 't1:DOD', x: 140, y: 390, line: lines.T1, name: 'Doonside' },
    // ...
    { id: 't1:BAK', x: 185, y: 390, line: lines.T1, name: 'Blacktown' },
    { id: 't1:SEV', x: 200, y: 390, line: lines.T1, name: 'Seven Hills' },
    { id: 't1:TGB', x: 215, y: 390, line: lines.T1, name: 'Toongabbie' },
    { id: 't1:PDH', x: 230, y: 390, line: lines.T1, name: 'Pendle Hill' },
    { id: 't1:WVL', x: 245, y: 390, line: lines.T1, name: 'Wentworthville' },
    { id: 't1:WMD', x: 260, y: 405, line: lines.T1, name: 'Westmead' },
    { id: 't1:PAR', x: 290, y: 435, line: lines.T1, name: 'Parramatta' },
    { id: 't1:HPK', x: 305, y: 450, line: lines.T1, name: 'Harris Park' },

    // ...NO COORDS...
    { id: 't1:GAV', x: 1, y: 2, images: [], line: lines.T1, name: 'Granville' },
    { id: 't1:CYE', x: 1, y: 2, images: [], line: lines.T1, name: 'Clyde' },
    { id: 't1:AUB', x: 1, y: 2, images: [], line: lines.T1, name: 'Auburn' },
    { id: 't1:LDC', x: 1, y: 2, images: [], line: lines.T1, name: 'Lidcombe' },
    { id: 't1:STR', x: 1, y: 2, images: [], line: lines.T1, name: 'Strathfield' },
    { id: 't1:REF', x: 1, y: 2, images: [], line: lines.T1, name: 'Redfern' },
    { id: 't1:CEN', x: 1, y: 2, images: [], line: lines.T1, name: 'Central' },
    { id: 't1:THL', x: 1, y: 2, images: [], line: lines.T1, name: 'Town Hall' },
    { id: 't1:WYN', x: 1, y: 2, images: [], line: lines.T1, name: 'Wynyard' },
    { id: 't1:MPT', x: 1, y: 2, images: [], line: lines.T1, name: 'Milsons Point' },
    { id: 't1:NSY', x: 1, y: 2, images: [], line: lines.T1, name: 'North Sydney' },
    { id: 't1:WVT', x: 1, y: 2, images: [], line: lines.T1, name: 'Waverton' },
    { id: 't1:WSC', x: 1, y: 2, images: [], line: lines.T1, name: 'Wollstonecraft' },
    { id: 't1:SNL', x: 1, y: 2, images: [], line: lines.T1, name: 'St Leonards' },
    { id: 't1:ATM', x: 1, y: 2, images: [], line: lines.T1, name: 'Artarmon' },
    { id: 't1:CWD', x: 1, y: 2, images: [], line: lines.T1, name: 'Chatswood' },
    { id: 't1:RVL', x: 1, y: 2, images: [], line: lines.T1, name: 'Roseville' },
    { id: 't1:LDD', x: 1, y: 2, images: [], line: lines.T1, name: 'Lindfield' },
    { id: 't1:KLA', x: 1, y: 2, images: [], line: lines.T1, name: 'Killara' },
    { id: 't1:GDN', x: 1, y: 2, images: [], line: lines.T1, name: 'Gordon' },
    { id: 't1:PYB', x: 1, y: 2, images: [], line: lines.T1, name: 'Pymble' },
    { id: 't1:TMU', x: 1, y: 2, images: [], line: lines.T1, name: 'Turramurra' },
    { id: 't1:WWE', x: 1, y: 2, images: [], line: lines.T1, name: 'Warrawee' },
    { id: 't1:WRO', x: 1, y: 2, images: [], line: lines.T1, name: 'Wahroonga' },
    { id: 't1:WTA', x: 1, y: 2, images: [], line: lines.T1, name: 'Waitara' },
    { id: 't1:HBY', x: 1, y: 2, images: [], line: lines.T1, name: 'Hornsby' },
    { id: 't1:ASQ', x: 1, y: 2, images: [], line: lines.T1, name: 'Asquith' },
    { id: 't1:MOC', x: 1, y: 2, images: [], line: lines.T1, name: 'Mount Colah' },
    { id: 't1:MKI', x: 1, y: 2, images: [], line: lines.T1, name: 'Mount Kuring-gai' },
    { id: 't1:BEW', x: 1, y: 2, images: [], line: lines.T1, name: 'Berowra' }

]

export const t1connections = [
    { start: 't1:RCD', end: 't1:ERD', line: lines.T1 },
    { start: 't1:ERD', end: 't1:CRD', line: lines.T1 },
    { start: 't1:CRD', end: 't1:WSR', line: lines.T1 },
    { start: 't1:WSR', end: 't1:MUV', line: lines.T1 },
    { start: 't1:MUV', end: 't1:VYR', line: lines.T1 },
    { start: 't1:VYR', end: 't1:RVS', line: lines.T1 },
    { start: 't1:RVS', end: 't1:SFS', line: lines.T1 },
    { start: 't1:SFS', end: 't1:QKH', line: lines.T1 },
    { start: 't1:QKH', end: 't1:MYG', line: lines.T1 },
    { start: 't1:MYG', end: 't1:BAK', line: lines.T1 },
    // ...
    { start: 't1:EPS', end: 't1:PNR', line: lines.T1 },
    { start: 't1:PNR', end: 't1:KWD', line: lines.T1 },
    { start: 't1:KWD', end: 't1:WRT', line: lines.T1 },
    { start: 't1:WRT', end: 't1:STM', line: lines.T1 },
    { start: 't1:STM', end: 't1:MTT', line: lines.T1 },
    { start: 't1:MTT', end: 't1:RYH', line: lines.T1 },
    { start: 't1:RYH', end: 't1:DOD', line: lines.T1 },
    { start: 't1:DOD', end: 't1:BAK', line: lines.T1 },
    // ...
    { start: 't1:BAK', end: 't1:SEV', line: lines.T1 },
    { start: 't1:SEV', end: 't1:TGB', line: lines.T1 },
    { start: 't1:TGB', end: 't1:PDH', line: lines.T1 },
    { start: 't1:PDH', end: 't1:WVL', line: lines.T1 },
    { start: 't1:WVL', end: 't1:WMD', line: lines.T1 },
    { start: 't1:WMD', end: 't1:PAR', line: lines.T1 },
    { start: 't1:PAR', end: 't1:HPK', line: lines.T1 },
    // ...
    { start: 't1:HPK', end: 't1:GAV', line: lines.T1 },
    { start: 't1:GAV', end: 't1:CYE', line: lines.T1 },
    { start: 't1:CYE', end: 't1:AUB', line: lines.T1 },
    { start: 't1:AUB', end: 't1:LDC', line: lines.T1 },
    { start: 't1:LDC', end: 't1:STR', line: lines.T1 },
    { start: 't1:STR', end: 't1:REF', line: lines.T1 },
    { start: 't1:REF', end: 't1:CEN', line: lines.T1 },
    { start: 't1:CEN', end: 't1:THL', line: lines.T1 },
    { start: 't1:THL', end: 't1:WYN', line: lines.T1 },
    { start: 't1:WYN', end: 't1:MPT', line: lines.T1 },
    { start: 't1:MPT', end: 't1:NSY', line: lines.T1 },
    { start: 't1:NSY', end: 't1:WVT', line: lines.T1 },
    { start: 't1:WVT', end: 't1:WSC', line: lines.T1 },
    { start: 't1:WSC', end: 't1:SNL', line: lines.T1 },
    { start: 't1:SNL', end: 't1:ATM', line: lines.T1 },
    { start: 't1:ATM', end: 't1:CWD', line: lines.T1 },
    { start: 't1:CWD', end: 't1:RVL', line: lines.T1 },
    { start: 't1:RVL', end: 't1:LDD', line: lines.T1 },
    { start: 't1:LDD', end: 't1:KLA', line: lines.T1 },
    { start: 't1:KLA', end: 't1:GDN', line: lines.T1 },
    { start: 't1:GDN', end: 't1:PYB', line: lines.T1 },
    { start: 't1:PYB', end: 't1:TMU', line: lines.T1 },
    { start: 't1:TMU', end: 't1:WWE', line: lines.T1 },
    { start: 't1:WWE', end: 't1:WRO', line: lines.T1 },
    { start: 't1:WRO', end: 't1:WTA', line: lines.T1 },
    { start: 't1:WTA', end: 't1:HBY', line: lines.T1 },
    { start: 't1:HBY', end: 't1:ASQ', line: lines.T1 },
    { start: 't1:ASQ', end: 't1:MOC', line: lines.T1 },
    { start: 't1:MOC', end: 't1:MKI', line: lines.T1 },
    { start: 't1:MKI', end: 't1:BEW', line: lines.T1 },
];
