import { lines } from '../constants';

// prettier-ignore
export const t5stations = [
    { id: 't5:RCD', x: 110, y: 200, line: lines.T5, name: 'Richmond' },
    { id: 't5:ERD', x: 110, y: 215, line: lines.T5, name: 'East Richmond' },    
    { id: 't5:CRD', x: 110, y: 230, line: lines.T5, name: 'Clarendon' },
    { id: 't5:WSR', x: 110, y: 245, line: lines.T5, name: 'Windsor' },
    { id: 't5:MUV', x: 110, y: 260, line: lines.T5, name: 'Mulgrave' },
    { id: 't5:VYR', x: 110, y: 275, line: lines.T5, name: 'Vineyard' },
    { id: 't5:RVS', x: 110, y: 290, line: lines.T5, name: 'Riverstone' },
    { id: 't5:SFS', x: 110, y: 305, line: lines.T5, name: 'Schofields' },
    { id: 't5:QKH', x: 110, y: 320, line: lines.T5, name: 'Quakers Hill' },
    { id: 't5:MYG', x: 110, y: 335, line: lines.T5, name: 'Marayong' },
    { id: 't5:BAK', x: 175, y: 400, line: lines.T5, name: 'Blacktown' },
    { id: 't5:SEV', x: 190, y: 400, line: lines.T5, name: 'Seven Hills' },
    { id: 't5:TGB', x: 205, y: 400, line: lines.T5, name: 'Toongabbie' },
    { id: 't5:PDH', x: 220, y: 400, line: lines.T5, name: 'Pendle Hill' },
    { id: 't5:WVL', x: 235, y: 400, line: lines.T5, name: 'Wentworthville' },
    { id: 't5:WMD', x: 250, y: 415, line: lines.T5, name: 'Westmead' },
    { id: 't5:PAR', x: 280, y: 445, line: lines.T5, name: 'Parramatta' },
    { id: 't5:HPK', x: 295, y: 460, line: lines.T5, name: 'Harris Park' },
    { id: 't5:MLN', x: 250, y: 505, line: lines.T5, name: 'Merrylands' },
    { id: 't5:GUD', x: 235, y: 520, line: lines.T5, name: 'Guildford' },
    { id: 't5:YNR', x: 235, y: 535, line: lines.T5, name: 'Yennora' },
    { id: 't5:FFL', x: 235, y: 550, line: lines.T5, name: 'Fairfield' },
    { id: 't5:CVE', x: 235, y: 565, line: lines.T5, name: 'Canley Vale' },
    { id: 't5:CAB', x: 235, y: 580, line: lines.T5, name: 'Cabramatta' },
    { id: 't5:WWF', x: 235, y: 595, line: lines.T5, name: 'Warwick Farm' },
    { id: 't5:LPO', x: 235, y: 610, line: lines.T5, name: 'Liverpool' },
    { id: 't5:CSL', x: 235, y: 625, line: lines.T5, name: 'Casula' },
    { id: 't5:GFD', x: 235, y: 640, line: lines.T5, name: 'Glenfield' },
    { id: 't5:EDP', x: 125, y: 640, line: lines.T5, name: 'Edmondson Park' },
    { id: 't5:LEP', x: 110, y: 640, line: lines.T5, name: 'Leppington' },
]

// prettier-ignore
export const t5connections = [
    { start: 't5:RCD', end: 't5:ERD', line: lines.T5 },
    { start: 't5:ERD', end: 't5:CRD', line: lines.T5 },
    { start: 't5:CRD', end: 't5:WSR', line: lines.T5 },
    { start: 't5:WSR', end: 't5:MUV', line: lines.T5 },
    { start: 't5:MUV', end: 't5:VYR', line: lines.T5 },
    { start: 't5:VYR', end: 't5:RVS', line: lines.T5 },
    { start: 't5:RVS', end: 't5:SFS', line: lines.T5 },
    { start: 't5:SFS', end: 't5:QKH', line: lines.T5 },
    { start: 't5:QKH', end: 't5:MYG', line: lines.T5 },
    { start: 't5:MYG', end: 't5:BAK', line: lines.T5 },
    { start: 't5:BAK', end: 't5:SEV', line: lines.T5 },
    { start: 't5:SEV', end: 't5:TGB', line: lines.T5 },
    { start: 't5:TGB', end: 't5:PDH', line: lines.T5 },
    { start: 't5:PDH', end: 't5:WVL', line: lines.T5 },
    { start: 't5:WVL', end: 't5:WMD', line: lines.T5 },
    { start: 't5:WMD', end: 't5:PAR', line: lines.T5 },
    { start: 't5:PAR', end: 't5:HPK', line: lines.T5 },
    { start: 't5:HPK', end: 't5:MLN', line: lines.T5 },
    { start: 't5:MLN', end: 't5:GUD', line: lines.T5 },
    { start: 't5:GUD', end: 't5:YNR', line: lines.T5 },
    { start: 't5:YNR', end: 't5:FFL', line: lines.T5 },
    { start: 't5:FFL', end: 't5:CVE', line: lines.T5 },
    { start: 't5:CVE', end: 't5:CAB', line: lines.T5 },
    { start: 't5:CAB', end: 't5:WWF', line: lines.T5 },
    { start: 't5:WWF', end: 't5:LPO', line: lines.T5 },
    { start: 't5:LPO', end: 't5:CSL', line: lines.T5 },
    { start: 't5:CSL', end: 't5:GFD', line: lines.T5 },
    { start: 't5:GFD', end: 't5:EDP', line: lines.T5 },
    { start: 't5:EDP', end: 't5:LEP', line: lines.T5 },
];
