import { lines } from './constants';
// import { codeToImage } from './images';

// prettier-ignore
export const t5stations = [
    { id: 't5:RCD', x: 110, y: 200, images: [], line: lines.T5, name: 'Richmond' },
    { id: 't5:ERD', x: 110, y: 215, images: [], line: lines.T5, name: 'East Richmond' },    
    { id: 't5:CRD', x: 110, y: 230, images: [], line: lines.T5, name: 'Clarendon' },
    { id: 't5:WSR', x: 110, y: 245, images: [], line: lines.T5, name: 'Windsor' },
    { id: 't5:MUV', x: 110, y: 260, images: [], line: lines.T5, name: 'Mulgrave' },
    { id: 't5:VYR', x: 110, y: 275, images: [], line: lines.T5, name: 'Vineyard' },
    { id: 't5:RVS', x: 110, y: 290, images: [], line: lines.T5, name: 'Riverstone' },
    { id: 't5:SFS', x: 110, y: 305, images: [], line: lines.T5, name: 'Schofields' },
    { id: 't5:QKH', x: 110, y: 320, images: [], line: lines.T5, name: 'Quakers Hill' },
    { id: 't5:MYG', x: 110, y: 335, images: [], line: lines.T5, name: 'Marayong' },
    { id: 't5:BAK', x: 175, y: 400, images: [], line: lines.T5, name: 'Blacktown' },
    { id: 't5:SEV', x: 190, y: 400, images: [], line: lines.T5, name: 'Seven Hills' },
    { id: 't5:TGB', x: 205, y: 400, images: [], line: lines.T5, name: 'Toongabbie' },
    { id: 't5:PDH', x: 220, y: 400, images: [], line: lines.T5, name: 'Pendle Hill' },
    { id: 't5:WVL', x: 235, y: 400, images: [], line: lines.T5, name: 'Wentworthville' },
    { id: 't5:WMD', x: 250, y: 415, images: [], line: lines.T5, name: 'Westmead' },
    { id: 't5:PAR', x: 280, y: 445, images: [], line: lines.T5, name: 'Parramatta' },
    { id: 't5:HPK', x: 295, y: 460, images: [], line: lines.T5, name: 'Harris Park' },
    { id: 't5:MLN', x: 250, y: 505, images: [], line: lines.T5, name: 'Merrylands' },
    { id: 't5:GUD', x: 235, y: 520, images: [], line: lines.T5, name: 'Guildford' },
    { id: 't5:YNR', x: 235, y: 535, images: [], line: lines.T5, name: 'Yennora' },
    { id: 't5:FFL', x: 235, y: 550, images: [], line: lines.T5, name: 'Fairfield' },
    { id: 't5:CVE', x: 235, y: 565, images: [], line: lines.T5, name: 'Canley Vale' },
    { id: 't5:CAB', x: 235, y: 580, images: [], line: lines.T5, name: 'Cabramatta' },
    { id: 't5:WWF', x: 235, y: 595, images: [], line: lines.T5, name: 'Warwick Farm' },
    { id: 't5:LPO', x: 235, y: 610, images: [], line: lines.T5, name: 'Liverpool' },
    { id: 't5:CSL', x: 235, y: 625, images: [], line: lines.T5, name: 'Casula' },
    { id: 't5:GFD', x: 235, y: 640, images: [], line: lines.T5, name: 'Glenfield' },
    { id: 't5:EDP', x: 125, y: 640, images: [], line: lines.T5, name: 'Edmondson Park' },
    { id: 't5:LEP', x: 110, y: 640, images: [], line: lines.T5, name: 'Leppington' },
]

export const t5connections = [
    { start: 't5:RCD', end: 't5:ERD', line: lines.T5 },
    { start: 't5:ERD', end: 't5:CRD', line: lines.T5 },
    { start: 't5:CRD', end: 't5:WSR', line: lines.T5 },
    { start: 't5:WSR', end: 't5:MUV', line: lines.T5 },
    { start: 't5:MUV', end: 't5:VYR', line: lines.T5 },
    { start: 't5:VYR', end: 't5:RVS', line: lines.T5 },
    { start: 't5:RVS', end: 't5:SFS', line: lines.T5 },
    { start: 't5:SFS', end: 't5:QKH', line: lines.T5 },
    { start: 't5:QKH', end: 't5:MYG', line: lines.T5 },
    { start: 't5:MYG', end: 't5:BAK', line: lines.T5 },
    { start: 't5:BAK', end: 't5:SEV', line: lines.T5 },
    { start: 't5:SEV', end: 't5:TGB', line: lines.T5 },
    { start: 't5:TGB', end: 't5:PDH', line: lines.T5 },
    { start: 't5:PDH', end: 't5:WVL', line: lines.T5 },
    { start: 't5:WVL', end: 't5:WMD', line: lines.T5 },
    { start: 't5:WMD', end: 't5:PAR', line: lines.T5 },
    { start: 't5:PAR', end: 't5:HPK', line: lines.T5 },
    { start: 't5:HPK', end: 't5:MLN', line: lines.T5 },
    { start: 't5:MLN', end: 't5:GUD', line: lines.T5 },
    { start: 't5:GUD', end: 't5:YNR', line: lines.T5 },
    { start: 't5:YNR', end: 't5:FFL', line: lines.T5 },
    { start: 't5:FFL', end: 't5:CVE', line: lines.T5 },
    { start: 't5:CVE', end: 't5:CAB', line: lines.T5 },
    { start: 't5:CAB', end: 't5:WWF', line: lines.T5 },
    { start: 't5:WWF', end: 't5:LPO', line: lines.T5 },
    { start: 't5:LPO', end: 't5:CSL', line: lines.T5 },
    { start: 't5:CSL', end: 't5:GFD', line: lines.T5 },
    { start: 't5:GFD', end: 't5:EDP', line: lines.T5 },
    { start: 't5:EDP', end: 't5:LEP', line: lines.T5 },
];

// T1

// prettier-ignore
export const t1stations = [
    { id: 't1:RCD', x: 120, y: 190, images: [], line: lines.T1, name: 'Richmond' },
    { id: 't1:ERD', x: 120, y: 205, images: [], line: lines.T1, name: 'East Richmond' },    
    { id: 't1:CRD', x: 120, y: 220, images: [], line: lines.T1, name: 'Clarendon' },
    { id: 't1:WSR', x: 120, y: 235, images: [], line: lines.T1, name: 'Windsor' },
    { id: 't1:MUV', x: 120, y: 250, images: [], line: lines.T1, name: 'Mulgrave' },
    { id: 't1:VYR', x: 120, y: 265, images: [], line: lines.T1, name: 'Vineyard' },
    { id: 't1:RVS', x: 120, y: 280, images: [], line: lines.T1, name: 'Riverstone' },
    { id: 't1:SFS', x: 120, y: 295, images: [], line: lines.T1, name: 'Schofields' },
    { id: 't1:QKH', x: 120, y: 310, images: [], line: lines.T1, name: 'Quakers Hill' },
    { id: 't1:MYG', x: 120, y: 325, images: [], line: lines.T1, name: 'Marayong' },
    { id: 't1:BAK', x: 185, y: 390, images: [], line: lines.T1, name: 'Blacktown' },
    { id: 't1:SEV', x: 200, y: 390, images: [], line: lines.T1, name: 'Seven Hills' },
    { id: 't1:TGB', x: 215, y: 390, images: [], line: lines.T1, name: 'Toongabbie' },
    { id: 't1:PDH', x: 230, y: 390, images: [], line: lines.T1, name: 'Pendle Hill' },
    { id: 't1:WVL', x: 245, y: 390, images: [], line: lines.T1, name: 'Wentworthville' },
    { id: 't1:WMD', x: 260, y: 405, images: [], line: lines.T1, name: 'Westmead' },
    { id: 't1:PAR', x: 290, y: 435, images: [], line: lines.T1, name: 'Parramatta' },
    { id: 't1:HPK', x: 305, y: 450, images: [], line: lines.T1, name: 'Harris Park' },
    // ...

    { id: 't1:EPS', x: 35, y: 390, images: [], line: lines.T1, name: 'Emu Plains' },
    { id: 't1:PNR', x: 50, y: 390, images: [], line: lines.T1, name: 'Penrith' },
    { id: 't1:KWD', x: 65, y: 390, images: [], line: lines.T1, name: 'Kingswood' },
    { id: 't1:WRT', x: 80, y: 390, images: [], line: lines.T1, name: 'Werrington' },
    { id: 't1:STM', x: 95, y: 390, images: [], line: lines.T1, name: 'St Marys' },
    { id: 't1:MTT', x: 110, y: 390, images: [], line: lines.T1, name: 'Mount Druitt' },
    { id: 't1:RYH', x: 125, y: 390, images: [], line: lines.T1, name: 'Rooty Hill' },
    { id: 't1:DOD', x: 140, y: 390, images: [], line: lines.T1, name: 'Doonside' },
]

export const t1connections = [
    { start: 't1:RCD', end: 't1:ERD', line: lines.T1 },
    { start: 't1:ERD', end: 't1:CRD', line: lines.T1 },
    { start: 't1:CRD', end: 't1:WSR', line: lines.T1 },
    { start: 't1:WSR', end: 't1:MUV', line: lines.T1 },
    { start: 't1:MUV', end: 't1:VYR', line: lines.T1 },
    { start: 't1:VYR', end: 't1:RVS', line: lines.T1 },
    { start: 't1:RVS', end: 't1:SFS', line: lines.T1 },
    { start: 't1:SFS', end: 't1:QKH', line: lines.T1 },
    { start: 't1:QKH', end: 't1:MYG', line: lines.T1 },
    { start: 't1:MYG', end: 't1:BAK', line: lines.T1 },
    { start: 't1:BAK', end: 't1:SEV', line: lines.T1 },
    { start: 't1:SEV', end: 't1:TGB', line: lines.T1 },
    { start: 't1:TGB', end: 't1:PDH', line: lines.T1 },
    { start: 't1:PDH', end: 't1:WVL', line: lines.T1 },
    { start: 't1:WVL', end: 't1:WMD', line: lines.T1 },
    { start: 't1:WMD', end: 't1:PAR', line: lines.T1 },
    { start: 't1:PAR', end: 't1:HPK', line: lines.T1 },
    // ...
    { start: 't1:EPS', end: 't1:PNR', line: lines.T1 },
    { start: 't1:PNR', end: 't1:KWD', line: lines.T1 },
    { start: 't1:KWD', end: 't1:WRT', line: lines.T1 },
    { start: 't1:WRT', end: 't1:STM', line: lines.T1 },
    { start: 't1:STM', end: 't1:MTT', line: lines.T1 },
    { start: 't1:MTT', end: 't1:RYH', line: lines.T1 },
    { start: 't1:RYH', end: 't1:DOD', line: lines.T1 },
    { start: 't1:DOD', end: 't1:BAK', line: lines.T1 },
];

export const t2stations = [
    {
        id: 't2:PAR',
        x: 280 - 10,
        y: 445 + 10,
        images: [],
        line: lines.T2,
        name: 'Parramatta',
    },
    {
        id: 't2:HPK',
        x: 295,
        y: 480,
        images: [],
        line: lines.T2,
        name: 'Harris Park',
    },
    {
        id: 't2:MLN',
        x: 250 + 10,
        y: 505 + 10,
        images: [],
        line: lines.T2,
        name: 'Merrylands',
    },
    {
        id: 't2:GUD',
        x: 235 + 10,
        y: 520 + 10,
        images: [],
        line: lines.T2,
        name: 'Guildford',
    },
    {
        id: 't2:YNR',
        x: 235 + 10,
        y: 535 + 10,
        images: [],
        line: lines.T2,
        name: 'Yennora',
    },
    {
        id: 't2:FFL',
        x: 235 + 10,
        y: 550 + 10,
        images: [],
        line: lines.T2,
        name: 'Fairfield',
    },
    {
        id: 't2:CVE',
        x: 235 + 10,
        y: 565 + 10,
        images: [],
        line: lines.T2,
        name: 'Canley Vale',
    },
    {
        id: 't2:CAB',
        x: 235 + 10,
        y: 580 + 10,
        images: [],
        line: lines.T2,
        name: 'Cabramatta',
    },
    {
        id: 't2:WWF',
        x: 235 + 10,
        y: 595 + 10,
        images: [],
        line: lines.T2,
        name: 'Warwick Farm',
    },
    {
        id: 't2:LPO',
        x: 235 + 10,
        y: 610 + 10,
        images: [],
        line: lines.T2,
        name: 'Liverpool',
    },
    {
        id: 't2:CSL',
        x: 235 + 10,
        y: 625 + 10,
        images: [],
        line: lines.T2,
        name: 'Casula',
    },
    {
        id: 't2:GFD',
        x: 235 + 10,
        y: 640 + 10,
        images: [],
        line: lines.T2,
        name: 'Glenfield',
    },
    {
        id: 't2:EDP',
        x: 125 + 10,
        y: 640 + 10,
        images: [],
        line: lines.T2,
        name: 'Edmondson Park',
    },
    {
        id: 't2:LEP',
        x: 110 + 10,
        y: 640 + 10,
        images: [],
        line: lines.T2,
        name: 'Leppington',
    },
];

export const t2connections = [
    { start: 't2:PAR', end: 't2:HPK', line: lines.T2 },
    { start: 't2:HPK', end: 't2:MLN', line: lines.T2 },
    { start: 't2:MLN', end: 't2:GUD', line: lines.T2 },
    { start: 't2:GUD', end: 't2:YNR', line: lines.T2 },
    { start: 't2:YNR', end: 't2:FFL', line: lines.T2 },
    { start: 't2:FFL', end: 't2:CVE', line: lines.T2 },
    { start: 't2:CVE', end: 't2:CAB', line: lines.T2 },
    { start: 't2:CAB', end: 't2:WWF', line: lines.T2 },
    { start: 't2:WWF', end: 't2:LPO', line: lines.T2 },
    { start: 't2:LPO', end: 't2:CSL', line: lines.T2 },
    { start: 't2:CSL', end: 't2:GFD', line: lines.T2 },
    { start: 't2:GFD', end: 't2:EDP', line: lines.T2 },
    { start: 't2:EDP', end: 't2:LEP', line: lines.T2 },
];

export const stations = [...t1stations, ...t5stations, ...t2stations];

export const connections = [
    ...t1connections,
    ...t5connections,
    ...t2connections,
];
